name: deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 22.16.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.1

      - name: build
        run: pnpm install && pnpm run build

      - name: deploy
        run: |
          mkdir -p /home/wn/deploy/app
          rm -rf /home/wn/deploy/app/*
          cp -r dist/* /home/wn/deploy/app/
          echo "deploy done"
